# SCA Scan using Trivy

name: SCA Scan

on:
  push:
    branches:
      - main
      - master

jobs:
  trivy-sca:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      # Trivy Scan
      - name: Run Trivy SCA scan
        uses: aquasecurity/trivy-action@0.28.0
        env:
          # https://github.com/aquasecurity/trivy/discussions/7668#discussioncomment-11141034
          TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db,aquasec/trivy-db,ghcr.io/aquasecurity/trivy-db
          TRIVY_JAVA_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-java-db,aquasec/trivy-java-db,ghcr.io/aquasecurity/trivy-java-db
        with:
          scan-type: 'fs'  # SCA scanning
          format: 'json'
          output: trivy-report.json
          directory: . 

      # Optional: Upload reports as artifact
      - name: Upload scan reports
        uses: actions/upload-artifact@v4
        with:
          name: sca-scan-reports
          path: |
            trivy-report.json