name: Semgrep Findings

on:
  push:
    branches:
      - main

jobs:
  semgrep-scan:
    name: Semgrep-Scan
    runs-on: ubuntu-20.04
    container:
      image: returntocorp/semgrep

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate with Semgrep (if using Pro/Enterprise)
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_API_KEY }}
        run: echo "Authenticated with Semgrep Pro"

      - name: Run Semgrep Scan
        run: |
          semgrep scan --json --json-output /tmp/semgrep.json
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_API_KEY }}  # Ensures API key is used during scan

      - name: Upload Semgrep Report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: /tmp/semgrep.json
